import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "City Fixer",
  description: "Generated by create next app",
};
import Navbar from "./Components/Navbar/Navbar";
import Banner from "./Components/Banner/Banner";
import Footer from "./Components/Footer/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header>
          {/* Navbar */}
          <Navbar></Navbar>

          {/* Banner */}
          <Banner></Banner>
        </header>

        {/* Main */}
        <main className="min-h-[calc(100vh-650px)]">{children}</main>

        {/* Footer */}
        <Footer></Footer>
      </body>
    </html>
  );
}
